#!/bin/bash

# Auto-training script for BPE tokenizer
# Runs for specified hours, generates text, trains, saves

HOURS=${1:-1}  # default 1 hour
VOCAB_SIZE=${2:-5000}
CORPUS_FILE="data/corpora/raw/auto_corpus.txt"
MODEL_FILE="model.json"

echo "Starting auto-training for $HOURS hours with vocab size $VOCAB_SIZE"

# Generate diverse training corpus
python3 << 'PYEOF'
import random
from pathlib import Path

words = [
    "hello", "world", "computer", "science", "artificial", "intelligence",
    "machine", "learning", "neural", "network", "deep", "learning", "data",
    "algorithm", "model", "training", "token", "vocabulary", "embed",
    "transformer", "attention", "layer", "batch", "epoch", "optimize",
    "gradient", "descent", "backpropagation", "activation", "function",
    "relu", "sigmoid", "softmax", "loss", "accuracy", "precision", "recall",
    "hello", "how", "are", "you", "today", "weather", "nice", "day",
    "morning", "evening", "night", "sleep", "wake", "eat", "drink",
    "walk", "run", "jump", "swim", "fly", "drive", "travel", "explore",
    "discover", "learn", "teach", "study", "work", "play", "create",
    "build", "design", "develop", "test", "deploy", "monitor", "scale",
    "happy", "sad", "angry", "excited", "bored", "tired", "hungry",
    "thirsty", "hot", "cold", "warm", "cool", "big", "small", "large",
    "tiny", "huge", "long", "short", "tall", "high", "low", "fast",
    "slow", "quick", "new", "old", "young", "modern", "ancient", "future",
    "past", "present", "time", "space", "world", "earth", "sun", "moon",
    "star", "sky", "cloud", "rain", "snow", "wind", "fire", "water",
    "land", "mountain", "river", "ocean", "forest", "desert", "city",
    "town", "village", "country", "nation", "people", "person", "man",
    "woman", "child", "baby", "family", "friend", "enemy", "stranger",
    "love", "hate", "like", "dislike", "want", "need", "have", "give",
    "take", "get", "make", "do", "go", "come", "see", "look", "watch",
    "hear", "listen", "speak", "say", "tell", "talk", "ask", "answer",
    "think", "know", "understand", "remember", "forget", "believe",
    "hope", "wish", "dream", "plan", "goal", "aim", "target", "purpose",
    "success", "failure", "win", "lose", "try", "attempt", "effort",
    "result", "effect", "cause", "reason", "because", "why", "how",
    "what", "when", "where", "who", "which", "this", "that", "these",
    "those", "one", "two", "three", "four", "five", "six", "seven",
    "eight", "nine", "ten", "hundred", "thousand", "million", "first",
    "second", "last", "next", "previous", "before", "after", "above",
    "below", "between", "among", "through", "across", "around", "over",
    "under", "inside", "outside", "within", "without", "beyond", "beside",
    "near", "far", "close", "distant", "here", "there", "everywhere",
    "nowhere", "somewhere", "anywhere", "everyone", "someone", "anyone",
    "noone", "nothing", "everything", "something", "anything", "always",
    "never", "often", "sometimes", "usually", "rarely", "frequently",
    "occasionally", "constantly", "continuously", "repeatedly", "daily",
    "weekly", "monthly", "yearly", "hourly", "minute", "moment", "instant",
    "second", "minute", "hour", "day", "week", "month", "year", "decade",
    "century", "millennium", "era", "epoch", "age", "period", "duration",
    "length", "width", "height", "depth", "size", "shape", "form", "figure",
    "pattern", "design", "structure", "framework", "system", "network",
    "web", "grid", "matrix", "array", "list", "queue", "stack", "tree",
    "graph", "chart", "diagram", "map", "plan", "scheme", "strategy",
    "tactic", "method", "approach", "technique", "process", "procedure",
    "protocol", "standard", "rule", "law", "regulation", "policy", "guideline",
    "principle", "value", "belief", "culture", "tradition", "custom",
    "habit", "routine", "practice", "exercise", "drill", "training",
    "education", "school", "college", "university", "student", "teacher",
    "professor", "doctor", "engineer", "scientist", "artist", "musician",
    "writer", "author", "poet", "novelist", "journalist", "reporter",
    "anchor", "host", "guest", "audience", "viewer", "listener", "reader",
    "user", "customer", "client", "patient", "passenger", "driver", "pilot",
    "captain", "crew", "team", "group", "band", "gang", "crowd", "mob",
    "herd", "flock", "pack", "swarm", "colony", "tribe", "clan", "family",
    "household", "home", "residence", "dwelling", "shelter", "building",
    "structure", "construction", "architecture", "design", "interior",
    "exterior", "facade", "roof", "wall", "floor", "ceiling", "window",
    "door", "gate", "fence", "wall", "barrier", "obstacle", "hurdle",
    "challenge", "difficulty", "problem", "issue", "trouble", "crisis",
    "emergency", "disaster", "catastrophe", "tragedy", "misfortune",
    "accident", "incident", "event", "occasion", "ceremony", "ritual",
    "celebration", "festival", "holiday", "vacation", "trip", "journey",
    "voyage", "expedition", "adventure", "quest", "mission", "operation",
    "campaign", "project", "program", "initiative", "enterprise", "venture",
    "business", "company", "corporation", "firm", "organization", "institution",
    "agency", "bureau", "office", "department", "division", "section",
    "unit", "team", "squad", "crew", "staff", "personnel", "workforce",
    "labor", "work", "job", "occupation", "profession", "career", "vocation",
    "calling", "mission", "purpose", "aim", "goal", "objective", "target",
    "destination", "endpoint", "finish", "conclusion", "end", "close",
    "closure", "completion", "fulfillment", "achievement", "accomplishment",
    "attainment", "realization", "actualization", "materialization", "fruition",
    "success", "victory", "triumph", "win", "gain", "profit", "benefit",
    "advantage", "edge", "lead", "upper", "dominant", "superior", "supreme",
    "ultimate", "final", "last", "definitive", "conclusive", "absolute",
    "total", "complete", "entire", "whole", "full", "comprehensive", "extensive",
    "broad", "wide", "vast", "immense", "enormous", "huge", "gigantic",
    "massive", "colossal", "titanic", "monumental", "prodigious", "stupendous",
    "astonishing", "amazing", "incredible", "unbelievable", "extraordinary",
    "remarkable", "exceptional", "outstanding", "phenomenal", "miraculous",
    "wonderful", "marvelous", "fabulous", "fantastic", "terrific", "great",
    "good", "fine", "nice", "pleasant", "enjoyable", "delightful", "lovely",
    "beautiful", "gorgeous", "stunning", "breathtaking", "spectacular",
    "magnificent", "splendid", "grand", "majestic", "impressive", "striking",
    "attractive", "charming", "elegant", "graceful", "refined", "sophisticated",
    "polished", "cultured", "civilized", "educated", "learned", "knowledgeable",
    "wise", "sage", "prudent", "sensible", "reasonable", "rational", "logical",
    "analytical", "critical", "thoughtful", "reflective", "contemplative",
    "meditative", "mindful", "aware", "conscious", "alert", "attentive",
    "focused", "concentrated", "dedicated", "committed", "devoted", "loyal",
    "faithful", "trustworthy", "reliable", "dependable", "responsible",
    "accountable", "answerable", "liable", "subject", "open", "susceptible",
    "vulnerable", "exposed", "unprotected", "defenseless", "helpless",
    "powerless", "weak", "feeble", "fragile", "delicate", "brittle", "frail",
    "sick", "ill", "unwell", "unhealthy", "diseased", "infected", "contaminated",
    "polluted", "toxic", "poisonous", "venomous", "dangerous", "hazardous",
    "risky", "perilous", "precarious", "uncertain", "doubtful", "questionable",
    "suspicious", "dubious", "skeptical", "cynical", "pessimistic", "negative",
    "adverse", "unfavorable", "hostile", "antagonistic", "aggressive",
    "belligerent", "combative", "militant", "warlike", "martial", "military",
    "armed", "weaponized", "loaded", "charged", "energized", "powered",
    "fueled", "driven", "motivated", "inspired", "encouraged", "supported",
    "backed", "funded", "financed", "sponsored", "endorsed", "approved",
    "authorized", "licensed", "certified", "qualified", "competent", "capable",
    "able", "skilled", "talented", "gifted", "blessed", "fortunate", "lucky",
    "favored", "preferred", "chosen", "selected", "elected", "appointed",
    "assigned", "designated", "named", "called", "termed", "labeled", "tagged",
    "marked", "branded", "stamped", "sealed", "signed", "endorsed", "approved",
    "accepted", "adopted", "embraced", "welcomed", "received", "greeted",
    "met", "encountered", "faced", "confronted", "challenged", "tested",
    "tried", "attempted", "endeavored", "strived", "struggled", "fought",
    "battled", "competed", "contended", "rivaled", "opposed", "resisted",
    "defied", "rebelled", "revolted", "mutinied", "protested", "demonstrated",
    "marched", "paraded", "processed", "moved", "advanced", "progressed",
    "developed", "evolved", "grown", "expanded", "extended", "stretched",
    "spread", "scattered", "dispersed", "distributed", "allocated", "allotted",
    "assigned", "apportioned", "divided", "split", "separated", "parted",
    "detached", "disconnected", "disjoined", "disunited", "alienated",
    "estranged", "isolated", "segregated", "excluded", "omitted", "left",
    "remained", "stayed", "persisted", "endured", "survived", "lasted",
    "continued", "maintained", "sustained", "preserved", "conserved", "kept",
    "held", "retained", "possessed", "owned", "had", "held", "grasped",
    "clutched", "clung", "adhered", "stuck", "attached", "connected", "linked",
    "joined", "united", "combined", "merged", "fused", "blended", "mixed",
    "mingled", "integrated", "incorporated", "included", "contained",
    "comprised", "composed", "constituted", "formed", "made", "created",
    "produced", "generated", "originated", "initiated", "started", "began",
    "commenced", "launched", "introduced", "presented", "offered", "proposed",
    "suggested", "recommended", "advised", "counseled", "guided", "directed",
    "led", "managed", "controlled", "regulated", "governed", "ruled",
    "commanded", "ordered", "dictated", "prescribed", "specified", "defined",
    "described", "explained", "clarified", "illuminated", "enlightened",
    "informed", "told", "reported", "announced", "declared", "stated",
    "asserted", "claimed", "maintained", "contended", "argued", "reasoned",
    "deduced", "inferred", "concluded", "determined", "decided", "resolved",
    "settled", "fixed", "established", "set", "placed", "put", "laid",
    "positioned", "situated", "located", "found", "discovered", "detected",
    "noticed", "observed", "perceived", "sensed", "felt", "experienced",
    "underwent", "suffered", "endured", "tolerated", "bore", "withstood",
    "resisted", "opposed", "fought", "combated", "countered", "refuted",
    "rejected", "denied", "disputed", "challenged", "questioned", "doubted",
    "suspected", "mistrusted", "distrusted", "feared", "dreaded", "terrified",
    "frightened", "scared", "alarmed", "warned", "cautioned", "advised",
    "counseled", "guided", "steered", "directed", "piloted", "navigated",
    "sailed", "cruised", "voyaged", "traveled", "journeyed", "toured",
    "visited", "saw", "viewed", "beheld", "witnessed", "observed", "noted",
    "recorded", "documented", "registered", "logged", "entered", "input",
    "fed", "supplied", "provided", "furnished", "equipped", "outfitted",
    "fitted", "suited", "adapted", "adjusted", "modified", "altered",
    "changed", "transformed", "converted", "transmuted", "translated",
    "interpreted", "rendered", "performed", "executed", "carried", "conducted",
    "managed", "handled", "treated", "dealt", "coped", "managed", "succeeded",
    "achieved", "accomplished", "completed", "finished", "ended", "closed",
    "concluded", "terminated", "ceased", "stopped", "halted", "paused",
    "interrupted", "suspended", "postponed", "delayed", "deferred", "put",
    "held", "kept", "retained", "reserved", "saved", "stored", "hoarded",
    "accumulated", "collected", "gathered", "assembled", "compiled",
    "composed", "written", "authored", "penned", "drafted", "drawn", "sketched",
    "outlined", "planned", "designed", "devised", "invented", "created",
    "originated", "initiated", "pioneered", "led", "spearheaded", "championed",
    "promoted", "advocated", "supported", "upheld", "defended", "protected",
    "guarded", "shielded", "screened", "sheltered", "harbored", "housed",
    "accommodated", "lodged", "quartered", "billeted", "stationed", "posted",
    "positioned", "deployed", "dispatched", "sent", "mailed", "shipped",
    "transported", "conveyed", "transferred", "moved", "shifted", "relocated",
    "resettled", "migrated", "immigrated", "emigrated", "fled", "escaped",
    "eluded", "evaded", "avoided", "shunned", "spurned", "rejected",
    "repudiated", "renounced", "abandoned", "deserted", "forsaken", "left",
    "departed", "exited", "withdrawn", "retreated", "receded", "returned",
    "come", "arrived", "reached", "attained", "achieved", "obtained",
    "acquired", "gained", "earned", "won", "secured", "procured", "purchased",
    "bought", "sold", "traded", "exchanged", "bartered", "negotiated",
    "bargained", "haggled", "argued", "debated", "discussed", "conversed",
    "chatted", "talked", "spoke", "uttered", "voiced", "expressed", "conveyed",
    "communicated", "transmitted", "broadcast", "published", "issued",
    "released", "launched", "unveiled", "revealed", "disclosed", "exposed",
    "uncovered", "discovered", "found", "detected", "located", "identified",
    "recognized", "known", "familiar", "acquainted", "aware", "conscious",
    "mindful", "cognizant", "sensible", "perceptive", "observant", "attentive",
    "alert", "vigilant", "watchful", "wary", "cautious", "careful", "prudent",
    "discreet", "tactful", "diplomatic", "politic", "strategic", "calculated",
    "planned", "intentional", "deliberate", "purposeful", "determined",
    "resolute", "decisive", "firm", "steadfast", "steadfast", "unwavering",
    "unshakable", "unyielding", "inflexible", "rigid", "stiff", "hard",
    "solid", "firm", "dense", "compact", "compressed", "condensed", "concentrated",
    "intense", "extreme", "severe", "harsh", "strict", "stern", "austere",
    "spartan", "ascetic", "disciplined", "controlled", "restrained", "moderate",
    "temperate", "measured", "balanced", "equable", "steady", "stable",
    "constant", "consistent", "uniform", "regular", "standard", "normal",
    "ordinary", "usual", "typical", "conventional", "traditional", "customary",
    "habitual", "routine", "common", "frequent", "prevalent", "widespread",
    "ubiquitous", "omnipresent", "universal", "global", "worldwide", "international",
    "national", "regional", "local", "provincial", "municipal", "urban",
    "rural", "suburban", "residential", "commercial", "industrial", "agricultural",
    "farming", "cultivation", "husbandry", "agronomy", "horticulture", "botany",
    "biology", "zoology", "ecology", "environment", "nature", "wildlife",
    "fauna", "flora", "vegetation", "plants", "trees", "shrubs", "bushes",
    "herbs", "grasses", "weeds", "flowers", "blooms", "blossoms", "fruits",
    "berries", "nuts", "seeds", "grains", "cereals", "crops", "harvest",
    "yield", "produce", "product", "output", "outcome", "result", "consequence",
    "effect", "impact", "influence", "affect", "sway", "bias", "prejudice",
    "predilection", "preference", "inclination", "tendency", "trend", "pattern",
    "style", "fashion", "mode", "manner", "way", "method", "means", "medium",
    "channel", "avenue", "route", "path", "course", "track", "trail", "lane",
    "road", "street", "avenue", "boulevard", "highway", "freeway", "motorway",
    "expressway", "turnpike", "tollway", "bridge", "tunnel", "overpass",
    "underpass", "crossing", "intersection", "junction", "confluence", "meeting",
    "gathering", "assembly", "congregation", "convention", "conference", "summit",
    "forum", "symposium", "seminar", "workshop", "class", "lesson", "lecture",
    "presentation", "speech", "address", "oration", "sermon", "homily",
    "discourse", "treatise", "dissertation", "thesis", "paper", "article",
    "essay", "composition", "manuscript", "document", "text", "script",
    "screenplay", "transcript", "record", "archive", "file", "dossier",
    "portfolio", "collection", "anthology", "compilation", "album", "catalog",
    "directory", "index", "register", "roll", "roster", "list", "schedule",
    "timetable", "calendar", "agenda", "itinerary", "program", "plan", "scheme",
    "blueprint", "diagram", "sketch", "draft", "outline", "summary", "abstract",
    "synopsis", "digest", "brief", "report", "account", "narrative", "story",
    "tale", "yarn", "anecdote", "episode", "incident", "event", "occurrence",
    "happening", "phenomenon", "experience", "adventure", "exploit", "feat",
    "deed", "act", "action", "activity", "operation", "exercise", "practice",
    "drill", "rehearsal", "preparation", "training", "instruction", "education",
    "learning", "study", "research", "investigation", "inquiry", "examination",
    "inspection", "scrutiny", "analysis", "evaluation", "assessment", "appraisal",
    "review", "critique", "criticism", "commentary", "interpretation", "explanation",
    "exposition", "description", "depiction", "portrayal", "representation",
    "image", "picture", "photograph", "snapshot", "shot", "frame", "scene",
    "view", "vista", "panorama", "landscape", "seascape", "cityscape",
    "portrait", "likeness", "resemblance", "semblance", "appearance", "look",
    "aspect", "facade", "front", "face", "surface", "exterior", "outside",
    "shell", "husk", "skin", "hide", "pelt", "fur", "hair", "wool", "feather",
    "plumage", "coat", "covering", "layer", "stratum", "level", "tier", "stage",
    "phase", "step", "degree", "grade", "rank", "class", "category", "group",
    "set", "batch", "lot", "parcel", "package", "packet", "bundle", "bunch",
    "cluster", "clump", "lump", "chunk", "block", "brick", "slab", "sheet",
    "plate", "panel", "pane", "screen", "shield", "guard", "protector",
    "defender", "champion", "advocate", "supporter", "backer", "sponsor",
    "patron", "benefactor", "donor", "contributor", "subscriber", "member",
    "participant", "player", "actor", "performer", "artist", "entertainer",
    "amateur", "hobbyist", "enthusiast", "fan", "follower", "admirer",
    "devotee", "disciple", "pupil", "student", "learner", "beginner", "novice",
    "trainee", "apprentice", "intern", "assistant", "aide", "helper", "worker",
    "laborer", "operative", "employee", "staffer", "crewman", "teammate",
    "partner", "colleague", "associate", "peer", "counterpart", "equivalent",
    "equal", "match", "mate", "companion", "comrade", "ally", "confederate",
    "collaborator", "cooperator", "co-worker", "fellow", "colleague", "peer"
]

# Generate paragraphs with random words
paragraphs = []
for _ in range(500):
    para = " ".join(random.choices(words, k=random.randint(20, 50)))
    paragraphs.append(para)

out = Path("data/corpora/raw/auto_corpus.txt")
out.parent.mkdir(parents=True, exist_ok=True)

with open(out, "w") as f:
    f.write("\n".join(paragraphs))

print(f"Generated corpus with {len(paragraphs)} paragraphs, {sum(len(p.split()) for p in paragraphs)} words")
PYEOF

# Train tokenizer
echo "Training tokenizer..."
cargo run -- --corpus "$CORPUS_FILE" --save "$MODEL_FILE" --vocab-size "$VOCAB_SIZE" --text "hello world"

# Test with sample texts
echo "Testing tokenization..."
cargo run -- --model model.json --text "artificial intelligence is transforming the world"
cargo run -- --model model.json --text "machine learning models require extensive training data"
cargo run -- --model model.json --text "neural networks can process complex patterns"

# Push to GitHub
echo "Pushing to GitHub..."
git add "$CORPUS_FILE" "$MODEL_FILE"
git commit -m "Auto-trained BPE tokenizer: vocab $VOCAB_SIZE, $(date)"
git push origin main

echo "Auto-training complete!"
